# Site settings
title:          Boyoung Lim's Notebook
description:    "세상을 깊게 보는 눈"
baseurl:        "/"
url:            "https://boyounglim.com"

# Google Analytics
#google_analytics: UA—XXXXXXXX-Xs

# Author
author:
  name:         Boyoung Lim
  url:          https://boyounglim.com
  email:        boyounglim88+2020@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

remote_theme: chesterhow/tale

# Permalinks
permalink:      /:year/:month/:day/:title
paginate:       10

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
#disqus:         jekyll-tale